import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export const runtime = "nodejs";

function esc(s: any) {
  return String(s ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function formatStamp(date = new Date()) {
  // simple “stamp” label; you can swap to real images later
  return date.toLocaleString();
}

function buildEmailHTML(opts: {
  companyName: string;
  tagline: string;
  primary: string;
  website?: string;
  formName: string;
  subject: string;
  to: string;
  stamp: string;
  formData: Record<string, any>;
  narrative?: string;
}) {
  const {
    companyName,
    tagline,
    primary,
    website,
    formName,
    subject,
    to,
    stamp,
    formData,
    narrative,
  } = opts;

  const rows = Object.entries(formData || {})
    .filter(([_, v]) => v !== undefined && v !== null && String(v).trim() !== "")
    .map(
      ([k, v]) => `
      <tr>
        <td style="padding:10px 12px;border:1px solid #e5e7eb;background:#f9fafb;width:35%;font-weight:600;color:#111827;">
          ${esc(k)}
        </td>
        <td style="padding:10px 12px;border:1px solid #e5e7eb;color:#111827;">
          ${esc(v)}
        </td>
      </tr>`
    )
    .join("");

  const narrativeBlock = narrative && narrative.trim()
    ? `
    <div style="margin-top:18px;">
      <div style="font-size:14px;font-weight:700;color:#111827;margin-bottom:8px;">Narrative</div>
      <div style="white-space:pre-wrap;background:#0b1220;color:#e5e7eb;border-radius:12px;padding:14px;line-height:1.45;">
        ${esc(narrative)}
      </div>
    </div>`
    : "";

  const websiteLine = website
    ? `<a href="${esc(website)}" style="color:${primary};text-decoration:none;">${esc(website)}</a>`
    : "";

  return `
<!doctype html>
<html>
  <body style="margin:0;background:#f3f4f6;padding:24px;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="max-width:760px;margin:0 auto;background:#ffffff;border-radius:18px;overflow:hidden;box-shadow:0 10px 30px rgba(0,0,0,.08);">
      <!-- Header -->
      <tr>
        <td style="padding:18px 20px;background:linear-gradient(135deg, ${primary}, #111827);color:#fff;">
          <div style="display:flex;align-items:center;justify-content:space-between;gap:12px;">
            <div>
              <div style="font-size:18px;font-weight:800;letter-spacing:.2px;">${esc(companyName)}</div>
              <div style="font-size:12px;opacity:.9;margin-top:2px;">${esc(tagline)}</div>
            </div>
            <div style="text-align:right;">
              <div style="display:inline-block;border:1px solid rgba(255,255,255,.35);padding:6px 10px;border-radius:999px;font-size:11px;letter-spacing:.6px;">
                OFFICIAL RECORD
              </div>
              <div style="font-size:11px;opacity:.95;margin-top:6px;">${esc(stamp)}</div>
            </div>
          </div>
        </td>
      </tr>

      <!-- Title -->
      <tr>
        <td style="padding:18px 20px 0 20px;">
          <div style="font-size:13px;color:#6b7280;">Form Submission</div>
          <div style="font-size:22px;font-weight:800;color:#111827;margin-top:4px;">
            ${esc(formName)}
          </div>
          <div style="margin-top:10px;padding:12px 14px;border:1px solid #e5e7eb;border-radius:14px;background:#fafafa;">
            <div style="font-size:12px;color:#6b7280;">Subject</div>
            <div style="font-size:14px;font-weight:700;color:#111827;margin-top:2px;">${esc(subject)}</div>
            <div style="font-size:12px;color:#6b7280;margin-top:8px;">Recipient</div>
            <div style="font-size:13px;color:#111827;margin-top:2px;">${esc(to)}</div>
          </div>
        </td>
      </tr>

      <!-- Fields -->
      <tr>
        <td style="padding:18px 20px;">
          <div style="font-size:14px;font-weight:700;color:#111827;margin-bottom:10px;">Details</div>
          <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;border-radius:12px;overflow:hidden;">
            ${rows || `
              <tr><td style="padding:12px;border:1px solid #e5e7eb;color:#6b7280;">No fields provided.</td></tr>
            `}
          </table>

          ${narrativeBlock}
        </td>
      </tr>

      <!-- Footer -->
      <tr>
        <td style="padding:16px 20px;background:#f9fafb;border-top:1px solid #e5e7eb;">
          <div style="font-size:12px;color:#6b7280;line-height:1.5;">
            This email was generated by ${esc(companyName)}. Please verify details against service policy and local directives.
            ${websiteLine ? `<div style="margin-top:6px;">${websiteLine}</div>` : ""}
          </div>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));

    const host = process.env.SMTP_HOST || "";
    const port = Number(process.env.SMTP_PORT || "587");
    const user = process.env.SMTP_USER || "";
    const pass = process.env.SMTP_PASS || "";
    const from = process.env.SMTP_FROM || user;
    const to = (body?.to || process.env.SMTP_TO_DEFAULT || user || "").trim();

    if (!host || !user || !pass) {
      return NextResponse.json(
        { ok: false, error: "SMTP env missing. Need SMTP_HOST/SMTP_USER/SMTP_PASS." },
        { status: 200 }
      );
    }
    if (!to) {
      return NextResponse.json({ ok: false, error: "Missing recipient 'to'." }, { status: 200 });
    }

    const subject = String(body?.subject || "Form Submission").trim();
    const formName = String(body?.formName || "EMS Form").trim();
    const formData = (body?.formData && typeof body.formData === "object") ? body.formData : {};
    const narrative = String(body?.narrative || "").trim();

    const companyName = process.env.COMPANY_NAME || "EffectiveAI";
    const tagline = process.env.COMPANY_TAGLINE || "EMS Assistant";
    const primary = process.env.COMPANY_PRIMARY_COLOR || "#2563eb";
    const website = process.env.COMPANY_WEBSITE || "";

    const html = buildEmailHTML({
      companyName,
      tagline,
      primary,
      website,
      formName,
      subject,
      to,
      stamp: formatStamp(new Date()),
      formData,
      narrative,
    });

    const transporter = nodemailer.createTransport({
      host,
      port,
      secure: port === 465, // 465 = SSL, 587 = STARTTLS
      auth: { user, pass },
    });

    const info = await transporter.sendMail({
      from,
      to,
      subject,
      html,
      // Optional plain text fallback
      text: `${formName}\n\n${subject}\n\n${JSON.stringify(formData, null, 2)}\n\n${narrative}`.trim(),
    });

    return NextResponse.json({ ok: true, messageId: info.messageId }, { status: 200 });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: String(e?.message || "Email send failed") }, { status: 200 });
  }
}