/*
===========================
FILE: /app/forms/occurrence/page.tsx
Form 1 UI (Construction occurrence / safety event report + AI summary + email)
===========================
*/
"use client";

import React, { useMemo, useState } from "react";
import { AppShell } from "@/src/app/components/shell/AppShell";
import { Card } from "@/src/app/components/ui/Card";
import { Field } from "@/src/app/components/ui/Field";
import { Select } from "@/src/app/components/ui/Select";
import { Button } from "@/src/app/components/ui/Button";
import { useAppState } from "@/src/app/components/state/AppState";

const REPORT_TO =
  process.env.NEXT_PUBLIC_REPORT_TO_EMAIL || "Team10@ConstructMatrix.net";

const LLM_ENDPOINT = "/api/llm";

function isoStamp() {
  return new Date().toISOString().slice(0, 16).replace("T", " ");
}

function fillOccurrenceDefaults(fd: Record<string, string>) {
  const stamp = isoStamp();
  const next = { ...(fd || {}) };

  const setIfMissing = (k: string, v: string) => {
    if (!next[k] || String(next[k]).trim() === "") next[k] = v;
  };

  setIfMissing("date", stamp.slice(0, 10));
  setIfMissing("time", stamp.slice(11));
  setIfMissing("projectName", "Demo Construction Project");
  setIfMissing("location", "Level 3 / East Elevation");
  setIfMissing("reportReference", "OCC-2026-0001");
  setIfMissing("eventType", "Hazard observation");
  setIfMissing("classification", "Safety");
  setIfMissing("classificationDetails", "Construction safety occurrence logged in-app.");
  setIfMissing("reportingParty", "Supervisor");
  setIfMissing("trade", "General labour");
  setIfMissing("equipmentAsset", "N/A");
  setIfMissing("sourceTierUsed", "Level 1 — Law & Regulator");
  setIfMissing(
    "briefSummary",
    "Demo safety event recorded during live system presentation."
  );
  setIfMissing(
    "observation",
    "Observed a condition requiring documentation and follow-up under site safety controls."
  );
  setIfMissing(
    "immediateAction",
    "Paused affected activity, documented condition, and notified site supervision."
  );
  setIfMissing(
    "correctiveAction",
    "Review task setup, confirm governing source, and close corrective actions before resuming work."
  );
  setIfMissing("supervisorReview", "Pending supervisor review.");
  setIfMissing("notifications", "Site supervision notified.");
  setIfMissing("ohsaImplication", "Review applicable Ontario construction requirements.");
  setIfMissing("aiSummary", "AI summary not generated.");
  return next;
}

function buildOccurrenceEmail(fd: Record<string, string>) {
  const g = (k: string) => (fd?.[k] || "").trim() || "—";

  const subject = `Construction Occurrence Report — ${g("reportReference")} — ${g("date")}`;

  const body = [
    "GLIP / ConstructMatrix — Construction Safety Intelligence",
    "CONSTRUCTION OCCURRENCE / SAFETY EVENT REPORT",
    `Generated: ${isoStamp()}`,
    "======================================",
    "",
    "Incident Overview",
    "----------------",
    `Date: ${g("date")}`,
    `Time: ${g("time")}`,
    `Project / Site: ${g("projectName")}`,
    `Location / Area: ${g("location")}`,
    `Report Reference: ${g("reportReference")}`,
    `Event Type: ${g("eventType")}`,
    "",
    `Brief Summary: ${g("briefSummary")}`,
    "",
    "Classification",
    `- Classification: ${g("classification")}`,
    `- Details: ${g("classificationDetails")}`,
    "",
    "People / Work Context",
    `- Reporting Party: ${g("reportingParty")}`,
    `- Trade / Crew: ${g("trade")}`,
    `- Equipment / Asset: ${g("equipmentAsset")}`,
    `- Source Tier Used: ${g("sourceTierUsed")}`,
    "",
    "Report Details",
    "Observation / Description:",
    g("observation"),
    "",
    "Immediate Action Taken:",
    g("immediateAction"),
    "",
    "Corrective / Preventive Action:",
    g("correctiveAction"),
    "",
    "Notifications:",
    g("notifications"),
    "",
    "Supervisor Review:",
    g("supervisorReview"),
    "",
    "OHSA / Regulatory Consideration:",
    g("ohsaImplication"),
    "",
    "AI Summary:",
    g("aiSummary"),
    "",
    "--------------------------------------",
    "Generated by GLIP construction safety workflow.",
    "Verify content against project requirements and Ontario construction obligations before operational use.",
  ].join("\n");

  return { subject, body };
}

export default function OccurrenceFormPage() {
  const { getFieldValue, setFieldValue, formData, dispatchAction, mentionedEmails } = useAppState();
  const [sending, setSending] = useState(false);
  const [summarizing, setSummarizing] = useState(false);
  const [toast, setToast] = useState("");

  const v = (id: string) => getFieldValue(id);
  const s = (id: string) => (val: string) => setFieldValue(id, val);

  const occ = formData?.occurrence || {};

  const preview = useMemo(() => {
    const g = (k: string) => (occ?.[k] || "").trim() || "—";
    return {
      date: g("date"),
      time: g("time"),
      projectName: g("projectName"),
      location: g("location"),
      eventType: g("eventType"),
      summary: g("briefSummary"),
      aiSummary: g("aiSummary"),
    };
  }, [occ]);

  async function clearForm() {
    dispatchAction({ type: "CLEAR_FORM", form: "occurrence" });
    dispatchAction({ type: "SET_FOCUS_FIELD", id: "occurrence.date" });
    setToast("Cleared.");
    setTimeout(() => setToast(""), 1200);
  }

  async function generateAiSummary() {
    if (summarizing) return;
    setSummarizing(true);
    setToast("");

    const current = fillOccurrenceDefaults(occ);

    try {
      const response = await fetch(LLM_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          provider: "auto",
          messages: [
            {
              role: "system",
              content: `
You are a construction safety reporting assistant.
You are helping prepare an Ontario construction occurrence report.

Return concise plain text with:
1. Summary
2. Immediate concerns
3. Recommended next steps
4. Supervisor note

Keep it practical and short.
Do not invent legal citations.
              `.trim(),
            },
            {
              role: "user",
              content: `
Generate an AI summary for this construction occurrence form:

${JSON.stringify(current, null, 2)}
              `.trim(),
            },
          ],
        }),
      });

      const data = await response.json().catch(() => ({}));

      if (!data?.ok || !data?.text) {
        throw new Error(data?.error || "AI summary failed");
      }

      setFieldValue("occurrence.aiSummary", String(data.text).trim());
      dispatchAction({
        type: "APPEND_CHAT_NOTE",
        text: "🤖 Construction occurrence AI summary generated.",
      });
      setToast("AI summary generated.");
      setTimeout(() => setToast(""), 1600);
    } catch (e: any) {
      setToast(`AI summary unavailable: ${String(e?.message || e)}`);
      setTimeout(() => setToast(""), 2200);
    } finally {
      setSummarizing(false);
    }
  }

  async function submitEmail() {
    if (sending) return;
    setSending(true);
    setToast("");

    const filled = fillOccurrenceDefaults(occ);

    for (const [k, val] of Object.entries(filled)) {
      setFieldValue(`occurrence.${k}`, String(val));
    }

    try {
      const { subject, body } = buildOccurrenceEmail(filled);
      const recipients =
        mentionedEmails && mentionedEmails.length > 0 ? mentionedEmails : [REPORT_TO];
      const toList = recipients.join(", ");

      const r = await fetch("/api/email", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ to: toList, subject, body }),
      });

      const data = await r.json().catch(() => ({}));

      if (data?.ok) {
        dispatchAction({
          type: "APPEND_CHAT_NOTE",
          text: `✅ Construction occurrence emailed to ${toList}: ${subject}`,
        });
        setToast(`✅ Sent to ${toList}`);
      } else {
        dispatchAction({
          type: "APPEND_CHAT_NOTE",
          text: `📨 SENT (DEMO MODE) — SMTP failed (${data?.error || "Unknown error"}) — ${subject}`,
        });
        setToast("📨 SENT (DEMO MODE) — SMTP failed");
      }
    } catch (e: any) {
      dispatchAction({
        type: "APPEND_CHAT_NOTE",
        text: `📨 SENT (DEMO MODE) — Email error (${String(e?.message || e)})`,
      });
      setToast("📨 SENT (DEMO MODE) — Email error");
    } finally {
      setSending(false);
      setTimeout(() => setToast(""), 2500);
    }
  }

  return (
    <AppShell>
      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <h2 className="text-lg font-semibold">Form 1 — Construction Occurrence Report</h2>
          <p className="mt-1 text-sm text-zinc-400">
            AI + voice can fill fields one at a time and generate a concise safety summary.
          </p>

          {toast ? (
            <div className="mt-3 rounded-2xl bg-black/30 px-3 py-2 text-xs text-zinc-200 shadow-inner">
              {toast}
            </div>
          ) : null}

          <div className="mt-5 space-y-5">
            <Section title="Incident Overview">
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                <Field
                  id="occurrence.date"
                  label="Date"
                  placeholder="YYYY-MM-DD"
                  value={v("occurrence.date")}
                  onChange={s("occurrence.date")}
                />
                <Field
                  id="occurrence.time"
                  label="Time"
                  placeholder="HH:MM"
                  value={v("occurrence.time")}
                  onChange={s("occurrence.time")}
                />
              </div>

              <Field
                id="occurrence.projectName"
                label="Project / site"
                placeholder="e.g., Toronto Tower Phase 2"
                value={v("occurrence.projectName")}
                onChange={s("occurrence.projectName")}
              />

              <Field
                id="occurrence.location"
                label="Location / area"
                placeholder="e.g., Level 8, south edge"
                value={v("occurrence.location")}
                onChange={s("occurrence.location")}
              />

              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                <Field
                  id="occurrence.reportReference"
                  label="Report reference"
                  placeholder="e.g., OCC-2026-0087"
                  value={v("occurrence.reportReference")}
                  onChange={s("occurrence.reportReference")}
                />
                <Select
                  id="occurrence.eventType"
                  label="Event type"
                  placeholder="Select"
                  options={[
                    "Hazard observation",
                    "Near miss",
                    "Equipment issue",
                    "Property damage",
                    "Worker concern",
                    "Environmental",
                    "Other",
                  ]}
                  value={v("occurrence.eventType")}
                  onChange={s("occurrence.eventType")}
                />
              </div>

              <Field
                id="occurrence.briefSummary"
                label="Brief summary"
                placeholder="Short summary of the event or condition"
                value={v("occurrence.briefSummary")}
                onChange={s("occurrence.briefSummary")}
              />
            </Section>

            <Section title="Classification">
              <Select
                id="occurrence.classification"
                label="Classification"
                placeholder="Select"
                options={[
                  "Safety",
                  "Operational",
                  "Equipment / maintenance",
                  "Environmental",
                  "Compliance",
                  "Other",
                ]}
                value={v("occurrence.classification")}
                onChange={s("occurrence.classification")}
              />

              <Field
                id="occurrence.classificationDetails"
                label="Classification details"
                placeholder="Additional classification details"
                value={v("occurrence.classificationDetails")}
                onChange={s("occurrence.classificationDetails")}
              />
            </Section>

            <Section title="People / Work Context">
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                <Field
                  id="occurrence.reportingParty"
                  label="Reporting party"
                  placeholder="Supervisor / worker / coordinator"
                  value={v("occurrence.reportingParty")}
                  onChange={s("occurrence.reportingParty")}
                />
                <Field
                  id="occurrence.trade"
                  label="Trade / crew"
                  placeholder="e.g., carpentry, electrical"
                  value={v("occurrence.trade")}
                  onChange={s("occurrence.trade")}
                />
              </div>

              <Field
                id="occurrence.equipmentAsset"
                label="Equipment / asset"
                placeholder="e.g., scissor lift EQ-2048"
                value={v("occurrence.equipmentAsset")}
                onChange={s("occurrence.equipmentAsset")}
              />

              <Select
                id="occurrence.sourceTierUsed"
                label="Source tier used"
                placeholder="Select"
                options={[
                  "Level 1 — Law & Regulator",
                  "Level 2 — Consensus Standards",
                  "Level 3 — Industry Frameworks",
                  "Level 4 — Manufacturer Instructions",
                  "Level 5 — Trade / Training Content",
                ]}
                value={v("occurrence.sourceTierUsed")}
                onChange={s("occurrence.sourceTierUsed")}
              />
            </Section>

            <Section title="Report Details">
              <Field
                id="occurrence.observation"
                label="Observation / description of event"
                placeholder="Describe what was observed..."
                textarea
                value={v("occurrence.observation")}
                onChange={s("occurrence.observation")}
              />

              <Field
                id="occurrence.immediateAction"
                label="Immediate action taken"
                placeholder="Describe immediate controls or actions..."
                textarea
                value={v("occurrence.immediateAction")}
                onChange={s("occurrence.immediateAction")}
              />

              <Field
                id="occurrence.correctiveAction"
                label="Corrective / preventive action"
                placeholder="Recommended steps to prevent recurrence..."
                textarea
                value={v("occurrence.correctiveAction")}
                onChange={s("occurrence.correctiveAction")}
              />

              <Field
                id="occurrence.notifications"
                label="Notifications"
                placeholder="Who was notified?"
                value={v("occurrence.notifications")}
                onChange={s("occurrence.notifications")}
              />

              <Field
                id="occurrence.supervisorReview"
                label="Supervisor review"
                placeholder="Notes for superintendent / supervisor review"
                textarea
                value={v("occurrence.supervisorReview")}
                onChange={s("occurrence.supervisorReview")}
              />

              <Field
                id="occurrence.ohsaImplication"
                label="OHSA / regulatory consideration"
                placeholder="What Ontario construction requirement may apply?"
                textarea
                value={v("occurrence.ohsaImplication")}
                onChange={s("occurrence.ohsaImplication")}
              />
            </Section>

            <Section title="AI Summary">
              <Field
                id="occurrence.aiSummary"
                label="AI summary"
                placeholder="Generate AI summary to fill this section"
                textarea
                value={v("occurrence.aiSummary")}
                onChange={s("occurrence.aiSummary")}
              />
            </Section>

            <div className="flex flex-col gap-2 sm:flex-row sm:justify-end">
              <Button variant="ghost" onClick={clearForm} disabled={sending || summarizing}>
                Clear
              </Button>
              <Button variant="ghost" onClick={generateAiSummary} disabled={sending || summarizing}>
                {summarizing ? "Generating…" : "Generate AI Summary"}
              </Button>
              <Button variant="primary" onClick={submitEmail} disabled={sending || summarizing}>
                {sending
                  ? "Sending…"
                  : `Submit (Email → ${
                      mentionedEmails && mentionedEmails.length > 0
                        ? mentionedEmails.join(", ")
                        : REPORT_TO
                    })`}
              </Button>
            </div>
          </div>
        </Card>

        <Card>
          <h3 className="text-sm font-medium">Live Form Preview</h3>
          <p className="mt-1 text-xs text-zinc-400">
            This is what will be used for summary and email output.
          </p>

          <div className="mt-4 rounded-2xl bg-black/30 p-4 text-sm text-zinc-200 shadow-inner">
            <div className="grid grid-cols-2 gap-3">
              <Preview k="Date" v={preview.date} />
              <Preview k="Time" v={preview.time} />
              <Preview k="Project" v={preview.projectName} />
              <Preview k="Location" v={preview.location} />
              <Preview k="Type" v={preview.eventType} />
              <Preview k="Summary" v={preview.summary} />
            </div>

            <div className="mt-4">
              <div className="text-xs uppercase tracking-wide text-zinc-500">AI Summary</div>
              <div className="mt-1 whitespace-pre-wrap text-zinc-300">{preview.aiSummary}</div>
            </div>
          </div>
        </Card>
      </div>
    </AppShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-zinc-400">{title}</div>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function Preview({ k, v }: { k: string; v: string }) {
  return (
    <div className="rounded-2xl bg-white/5 p-3 shadow-[0_0_0_1px_rgba(255,255,255,.08)]">
      <div className="text-[10px] uppercase tracking-wide text-zinc-500">{k}</div>
      <div className="mt-1 font-medium">{v}</div>
    </div>
  );
}